name: Build PDF

on: [push]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install TeXLive
        uses: zauguin/install-texlive@v3
        with:
          packages: >-
            latex latex-bin luatex latex-bin-dev latexmk scheme-basic
            beamer grffile graphbox babel-english beamerposter caption booktabs qrcode 
            xkeyval snapshot type1cm fp
      - name: LaTeX compilation
        run: latexmk -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode poster.tex || true
      - uses: actions/upload-artifact@v4
        with: 
          name: poster
          path: poster.pdf
          compression-level: 0
