name: Build PDF

on: [push]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: LaTeX compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: poster.tex
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - uses: actions/upload-artifact@v4
        with: 
          name: poster
          path: poster.pdf
          compression-level: 0
