name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        asset_name: 
          - poster.pdf
    steps:
      - uses: actions/checkout@v4
      - name: Install TeXLive
        uses: zauguin/install-texlive@v3
        with:
          packages: >-
            latex latex-bin luatex latex-bin-dev latexmk scheme-basic
            beamer grffile graphbox babel-english beamerposter caption booktabs qrcode 
            xkeyval snapshot type1cm fp
      - name: LaTeX compilation
        run: latexmk -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode poster.tex || true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true